### ISSUE TITLE
TTS resonator fit. Case: wide resonator swing from flux 

### ISSUE THREAD

**Issue by shamil777** [vdrhtc/Measurement-automation#4]
As you can see on the image below (single tone spectroscopy BMSTU 007-1 sample resonator №0)
resonator frequency varies from 5.3 to 5.55 GHz approximately. 
Suppose:
1. There is no direct anticrossings between resonator and qubit lines 
2. Transmon qubits TTS spectrum is completely above the resonator line, but its lower sweet-spots are close enough to the resonator to cause such a wide swing of the resonator frequency.
![i-sts-coil](https://user-images.githubusercontent.com/23475057/50538287-1eadc400-0b7e-11e9-8de1-e05245f6eaae.png)
In contrast resonator width is relatively small and equals 1 MHz at most:
![1](https://user-images.githubusercontent.com/23475057/50538365-b4961e80-0b7f-11e9-9b03-e6fd67ebb136.png)

In this case it is painful to measure TTS in the range of flux where resonator frequency varies significantly. The reason is that we need to fit resonator for every vertical line of the TTS measurement. 
Thus, we need to provide a range of frequencies where we would like to find and fit resonator. Fitting process from resonator_tools works best when the frequency width of the data is somewhat near to 5-6 resonator width. 
So, in the current case:
1. We are choosing to measure TTS in range (-1e-4,-0.3e-4) where resonator frequency lies in (5.330, 5.355) - 15 MHz interval.
2. We are setting resonator frequency range = (5.33, 5.355) that is at least 15 times larger than the resonator width.
3. For every flux point resonator fit process, script is trying to fit the whole (5.33, 5.355) with a resonator and fails due to the enourmous width of the range.

This setup lacks of anticrossings -> we are able to measure TTS almost everywhere. But what a crash, our fit model cannot work in wide frequency range that is much wider than the resonator width!

I propose to find resonator with a sliding window technique during the first run and then trying to track down the resonator position that varies with the flux. Tracktion is based on prediction that relies on the previous resonator and successful sliding window positions. 
Algorithm should be something like:
1. If this is the first flux point -> get full frequency sweep around resonator and try to find resonator with a sliding window of appropriate width (default - couple MHz enough I assume, or provided by the user via FastTwoToneSpectroscopy.set_fixed_params). Store the successful sliding window position (*f1*,*f2*) and the resonator frequency - *rfreq*.
Cycle:
2. Measure TTS in this flux point and change flux to the next one flux point.
3.1 *If two last successful sliding windows positions for two last flux points are available*:
predict new sliding window position and try to fit resonator. If succeeds -> goto 2, else -> goto 3.2
3.2 *else*:
Try to find a resonator withing the sliding window that successfuly fitted the resonator in the previous flux point. 
If success -> goto 2
else
3.2.1 Try to fit resonator using neighbour sliding window positions (to the left and to the right from the last successful position, the step is deduced from the resonator frequency)
If success -> goto 2
If failed -> perform one more finding cycle that is described in 1. if succeed -> goto 2 else -> goto 2 but new resonator frequency is the same as during the previous step

**Comment by vdrhtc** [comment]
If I am not mistaken, the sliding window is already implemented in a crude form in TTS, see line 70 in [TwoToneSpectroscopy.py](https://github.com/vdrhtc/Measurement-automation/blob/master/lib2/TwoToneSpectroscopy.py)

We only need to make it adaptive, then...

**Comment by vdrhtc** [comment]
Works all right in the current form, without predicting the next position by two previous ones, but just using the last result

https://github.com/vdrhtc/Measurement-automation/blob/62bd6f18abd588b0a743b20d5e22dbe1f02b8401/lib2/TwoToneSpectroscopy.py#L44-L77
